### ISSUE TITLE
Can't Download Precompiled Binaries

### ISSUE THREAD

**Issue by bgosse2010** [rochus-keller/OberonSystem3#1]
For security reasons both a Chrome or Edge are blocking the download of the precompiled binaries. Here's Edge's message:
This file can't be downloaded securely
Malicious attackers might be able to read or change insecurely downloaded files.
[Learn more](https://go.microsoft.com/fwlink/?linkid=2123938&clcid=0x409)

Chrome complains about multiple files being downloaded.

This is just an FYI for you.

**Comment by rochus-keller** [comment]
I can download it using these browers on Windows 10 and 11 by right-klicking on the link and "save as"; in times a bubble appears top right to the URL stating that it is dangerous, but I still can continue. 

If all that fails, you can still copy the URL (e.g. by right-click on the link and select "copy address") and paste it directly into the URL field of the browser.

We are apparently striving for a time when people will be completely disenfranchised by browser manufacturers (i.e. big-tech companies) with security as an excuse.
